export const COMPONENTS_SAMPLE_PAGE_2_LOAD_SUCCESS = 'COMPONENTS_SAMPLE_PAGE_2_LOAD_SUCCESS';
export const COMPONENTS_SAMPLE_PAGE_2_SPINNER_START = 'COMPONENTS_SAMPLE_PAGE_2_SPINNER_START';
export const PATIENT_FULL_NAME = 'PATIENT_FULL_NAME';
export const PATIENT_EMAIL_ADDRESS ='PATIENT_EMAIL_ADDRESS';
